package sample.main.mPojos;

public class FeesPayment {

    private int id;
    private String studentRegnumber;
    private String paymentMethod;
    private String transactionID;
    private String paidAmount;
    private String datePaid;
    private String bank;
    private String bankAccount;
    private String payedBy;
    private String balanceRemaining;
    private String termPaid;
    private float discount;

    /**
     * Payment Object
     * @param id    Auto generated by the table as new records get added
     * @param studentRegnumber  the student paying
     * @param paymentMethod was it done using cash or mobile bank or banks
     * @param transactionID id for the transaction
     * @param paidAmount    paid amount
     * @param datePaid  date will be generated by the system not shown to the user but shown grom viewing table
     * @param bank  bank names usedif payment method was not cash
     * @param bankAccount   account of the bak for the money is comming from if payment was done using the bank method
     * @param payedBy   The name of the person who made the actual payment
     * @param balanceRemaining  the calculated balance remaining
     * @param termPaid  which term is this being paid
     * @param discount
     */
    public FeesPayment (int id, String studentRegnumber, String paymentMethod, String transactionID, String paidAmount, String datePaid, String bank, String bankAccount, String payedBy, String balanceRemaining, String termPaid, float discount) {
        this.id = id;
        this.studentRegnumber = studentRegnumber;
        this.paymentMethod = paymentMethod;
        this.transactionID = transactionID;
        this.paidAmount = paidAmount;
        this.datePaid = datePaid;
        this.bank = bank;
        this.bankAccount = bankAccount;
        this.payedBy = payedBy;
        this.balanceRemaining = balanceRemaining;
        this.termPaid = termPaid;
        this.discount = discount;
    }

    public int getId () {
        return id;
    }

    public void setId (int id) {
        this.id = id;
    }

    public String getStudentRegnumber () {
        return studentRegnumber;
    }

    public void setStudentRegnumber (String studentRegnumber) {
        this.studentRegnumber = studentRegnumber;
    }

    public String getPaymentMethod () {
        return paymentMethod;
    }

    public void setPaymentMethod (String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getTransactionID () {
        return transactionID;
    }

    public void setTransactionID (String transactionID) {
        this.transactionID = transactionID;
    }

    public String getPaidAmount () {
        return paidAmount;
    }

    public void setPaidAmount (String paidAmount) {
        this.paidAmount = paidAmount;
    }

    public String getDatePaid () {
        return datePaid;
    }

    public void setDatePaid (String datePaid) {
        this.datePaid = datePaid;
    }

    public String getBank () {
        return bank;
    }

    public void setBank (String bank) {
        this.bank = bank;
    }

    public String getBankAccount () {
        return bankAccount;
    }

    public void setBankAccount (String bankAccount) {
        this.bankAccount = bankAccount;
    }

    public String getPayedBy () {
        return payedBy;
    }

    public void setPayedBy (String payedBy) {
        this.payedBy = payedBy;
    }

    public String getBalanceRemaining () {
        return balanceRemaining;
    }

    public void setBalanceRemaining (String balanceRemaining) {
        this.balanceRemaining = balanceRemaining;
    }

    public String getTermPaid () {
        return termPaid;
    }

    public void setTermPaid (String termPaid) {
        this.termPaid = termPaid;
    }

    public float getDiscount () {
        return discount;
    }

    public void setDiscount (float discount) {
        this.discount = discount;
    }
}
